services:
  backend-develop:
    build: .
    container_name: enlacecrm_backend_develop
    ports:
      - "2001:3001"   
    env_file:
      - .env
    environment:
      - PORT=3001
      - NODE_ENV=dev
    restart: always
    volumes:
      - .:/app
    command: npm start
    networks:
      - enlace-net

networks:
  enlace-net:
    external: true
