services:
  backend:
    build: .
    container_name: enlacecrm_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
    restart: always
    volumes:
      - .:/app
    command: npm start
    networks: 
      - enlace-net
networks:
  enlace-net:
    external: true
