apiVersion: apps/v1
kind: Deployment
metadata:
  name: enlacecrm-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enlacecrm-backend
  template:
    metadata:
      labels:
        app: enlacecrm-backend
    spec:
      automountServiceAccountToken: false
      containers:
       - name: enlacecrm-backend
         image: milydemendoza/enlacecrm-backend:1.0.3
         resources:
           requests:
             cpu: "500m"
             memory: "256Mi"
             ephemeral-storage: "1Gi"
           limits:
             cpu: "1"
             memory: "512Mi"
             ephemeral-storage: "2Gi"
         ports:
         - containerPort: 8082
           name: http
