apiVersion: v1
kind: Service
metadata:
  name: enlacecrm-backend-service
spec:
  selector:
    app: enlacecrm-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
